name: Off_Duty_Reminder
on:
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send Off duty reminder 

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./Off_Duty_Reminder.py

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      LOW_WORK_TEMPLATE_ID: ${{ secrets.LOW_WORK_TEMPLATE_ID }}
      BOY_FRIEND_ID: ${{ secrets.BOY_FRIEND_ID }}
      GIRL_FRIEND_ID: ${{ secrets.GIRL_FRIEND_ID }}

